repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.285
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        # exclude: ^gui.py
  - repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
      - id: black
        # exclude: ^gui.py
